package:
  name: "riverrem"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/OpenTopography/RiverREM

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - gdal
    - scipy
    - osmnx
    - shapely
    - geopandas
    - dataclasses

about:
  home: https://github.com/OpenTopography/RiverREM
  license: BSD 3-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "Make river relative elevation models (REMs) from an input digital elevation model (DEM)."

extra:
  recipe-maintainers:
    - klarrieu